name: Release CI

on:
  push:
    branches:
      - branch-2.3

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'
          distribution: 'adopt'

      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_READ_WRITE }}
        run: sbt test

      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_READ_WRITE }}
        run: sbt package

      - name: Publish with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_READ_WRITE }}
        run: sbt publish
