name: Release CI

on:
  push:
    branches:
      - branch-2.4

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_READ_WRITE }}
        run: sbt ++test

      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_READ_WRITE }}
        run: sbt ++package

      - name: Publish with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_READ_WRITE }}
        run: sbt ++publish
