name: Space Filling Curve CI

on:
  push:
    branches:
      - main
      - feature/*
      - dev/*
      - release/*
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt -mem 2048 test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}