name: Space Filling Curve CI

on:
  push:
    branches:
      - main
      - feature/*
      - dev/*
      - release/*
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11']

    steps:
      - name: Set up JVM
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Run tests
        run: sbt -mem 2048 test
