name: Space Filling Curve CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'
          distribution: 'adopt'
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_READ_WRITE }}
        run: |
          sbt compile
          sbt test
