name: Space Filling Curve CI

on:
  push:
    branches:
      - main
      - feature/*
      - dev/*
      - release/*
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JVM
      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run tests
      - uses: actions/checkout@v2
        run: sbt -mem 2048 test
